spring:
  application:
    name: ms-denuncias
  config:
    # IMPORTANTE: Configuración híbrida. Usa la variable de entorno en Azure, o localhost por defecto.
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"

eureka:
  client:
    serviceUrl:
      # IMPORTANTE: Usa variable de entorno en Azure, o localhost por defecto.
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
