# Configuraci√≥n del gateway
spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: ms-auth-root-paths
              uri: ${URI_MS_AUTH:http://localhost:9092}
              predicates:
                - Path=/oauth2/**,/login/**

            - id: ms-auth
              uri: ${URI_MS_AUTH:http://localhost:9092}
              predicates:
                - Path=/auth/**
              filters:
                - StripPrefix=1

            - id: ms-usuarios
              uri: ${URI_MS_USUARIOS:http://localhost:9091}
              predicates:
                - Path=/usuarios/**,/interno/usuarios/**

            - id: ms-denuncias
              uri: ${URI_MS_DENUNCIAS:http://localhost:8083}
              predicates:
                - Path=/api/denuncias/**

            - id: ms-evidencias
              uri: ${URI_MS_EVIDENCIAS:http://localhost:8090}
              predicates:
                - Path=/interno/adjuntar/**,/interno/entidades/**,/interno/uploads/**,/interno/*/confirmar

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${ISSUER_URI:http://localhost:9092}

server:
  port: 8081

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.web: DEBUG
    org.springframework.cloud.gateway.server.mvc: DEBUG
    org.springframework.web.servlet.function: DEBUG
