# Configuración de la aplicación ms-auth
spring:
  application:
    name: ms-auth
  mail:
    host: ${MAIL_HOST:}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USER:postgres.your-id-on-supabase}
    password: ${DB_PASSWORD:your-password-on-supabase}
    url: ${DB_URL:jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:5432/postgres}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 60000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: ms_auth
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 9092
  forward-headers-strategy: framework
  forward-headers-strategy: framework

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.web: DEBUG
    org.springframework.security.oauth2.server.authorization: DEBUG

app:
  security:
    issuer: ${AUTH_ISSUER:http://localhost:9092}
    client:
      id: ${AUTH_CLIENT_ID:ds-web}
      redirect-uris: ${AUTH_REDIRECT_URIS:http://localhost:4200/dashboard,https://oauth.pstmn.io/v1/callback}
    reset-url: ${RESET_URL:http://localhost:5173/reset-password?token=}

ms-usuarios:
  url: ${MS_USUARIOS_URL:http://localhost:9091}
