spring:
  application:
    name: ms-auth
  config:
    # IMPORTANTE: Configuración híbrida. Usa la variable de entorno en Azure, o localhost por defecto.
    import: "optional:configserver:${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}"

eureka:
  instance:
    prefer-ip-address: false
    hostname: ms-auth.internal.wittyriver-e5cd2ef5.eastus.azurecontainerapps.io
    non-secure-port: 80
    non-secure-port-enabled: true