
logging:
  loki:
    url: https://logs-prod-024.grafana.net/loki/api/v1/push
    user: ${GRAFANA_USER}
    token: ${GRAFANA_TOKEN}

management:
  otlp:
    metrics:
      export:
        url: https://otlp-gateway-prod-sa-east-1.grafana.net/otlp/v1/metrics
        headers:
          Authorization: ${GRAFANA_AUTH}

  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: https://otlp-gateway-prod-sa-east-1.grafana.net/otlp/v1/traces
          protocol: http
          headers:
            Authorization: ${GRAFANA_AUTH}

    logging:
      export:
        enabled: false