name: Deploy Production to Azure (Hotfix)

on:
  push:
    branches: [ hotfix ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        service: [ms-configServer, ms-eureka, ms-auth, ms-usuarios, ms-evidencias, ms-denuncias, gateway]

    steps:
      - uses: actions/checkout@v4

      # Preparar Java 25
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'
          cache: 'maven'

      # 1. Compilar el proyecto completo
      - name: Build with Maven
        run: mvn -B -DskipTests clean package

      # 2. Login en Azure (USANDO CREDENCIALES HOTFIX)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_HOTFIX }}

      # 3. Login en Docker Registry (USANDO CREDENCIALES HOTFIX)
      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER_HOTFIX }}
          username: ${{ secrets.REGISTRY_USERNAME_HOTFIX }}
          password: ${{ secrets.REGISTRY_PASSWORD_HOTFIX }}

      # 4. Normalizar nombre del servicio
      - name: Lowercase Service Name
        id: service_name
        run: |
          echo "LOWER_NAME=$(echo ${{ matrix.service }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      # 5. Construir y Subir Imagen (USANDO REGISTRY HOTFIX)
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: ./${{ matrix.service }}
          file: ./${{ matrix.service }}/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER_HOTFIX }}/${{ env.LOWER_NAME }}:${{ github.sha }},${{ secrets.REGISTRY_LOGIN_SERVER_HOTFIX }}/${{ env.LOWER_NAME }}:latest

      # 6. Desplegar a Azure Container Apps (USANDO SECRETOS HOTFIX)
      - name: Deploy to ACA
        uses: azure/container-apps-deploy-action@v1
        with:
          containerAppName: ${{ env.LOWER_NAME }}
          resourceGroup: rg-denuncia-segura-v2
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER_HOTFIX }}/${{ env.LOWER_NAME }}:${{ github.sha }}
          registryUrl: ${{ secrets.REGISTRY_LOGIN_SERVER_HOTFIX }}
          registryUsername: ${{ secrets.REGISTRY_USERNAME_HOTFIX }}
          registryPassword: ${{ secrets.REGISTRY_PASSWORD_HOTFIX }}

          # Optimización para cuenta de estudiante (para que no se acabe la quota)
          cpu: 0.5
          memory: 1.0Gi

          # Puertos específicos
          targetPort: ${{ matrix.service == 'ms-eureka' && 8761 || matrix.service == 'ms-configServer' && 8888 || 8080 }}
          ingress: internal